import { createFileRoute } from "@tanstack/react-router";
import { Camera, Check, Eye, Link2, Mail, MapPin, Pencil, UserRound } from "lucide-react";
import { toast } from "sonner";
import { PageIntro } from "@/components/dashboard/ModulePage";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { viewer } from "@/data/dashboard";

export const Route = createFileRoute("/dashboard/profile")({ head: () => ({ meta: [{ title: "Profile — FolioX" }, { name: "description", content: "Shape your professional profile and visibility in FolioX." }, { property: "og:title", content: "Profile — FolioX" }, { property: "og:description", content: "Manage your FolioX professional profile." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: ProfilePage });

const details = [[UserRound,"Personal information","Amara Okafor · she/her"],[Pencil,"Professional headline",viewer.headline],[Mail,"Contact information",viewer.email],[MapPin,"Location","Lagos, Nigeria · Available remotely"],[Link2,"Professional links","2 public links"],[Eye,"Profile visibility","Public profile"]] as const;
function ProfilePage() { return <div className="space-y-8"><PageIntro eyebrow="Professional identity" title="Profile" description="Shape the foundation of how people understand your work, expertise, and professional direction." action={<Button onClick={() => toast.message("Profile editor preview", { description: "Saving will be available when account data is connected." })} className="rounded-full"><Pencil/>Edit profile</Button>}/><section className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><div className="rounded-2xl border border-border bg-card p-6 shadow-soft"><div className="relative mx-auto grid size-28 place-items-center rounded-full bg-highlight font-display text-3xl font-bold">{viewer.initials}<button aria-label="Change profile photo" className="absolute bottom-0 right-0 grid size-9 place-items-center rounded-full bg-primary text-primary-foreground shadow-accent"><Camera className="size-4"/></button></div><div className="mt-5 text-center"><h2 className="font-display text-xl font-bold">{viewer.fullName}</h2><p className="mt-1 text-xs text-muted-foreground">{viewer.headline}</p></div><div className="mt-7 rounded-xl bg-subtle p-4"><div className="flex items-center justify-between text-xs font-bold"><span>Profile strength</span><span>83%</span></div><Progress value={83} className="mt-3"/><p className="mt-3 text-xs leading-5 text-muted-foreground">Add a profile photo to complete your core profile.</p></div></div><div className="grid gap-3 sm:grid-cols-2">{details.map(([Icon,title,value]) => <article key={title} className="rounded-xl border border-border bg-card p-5 shadow-soft"><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-lg bg-accent-soft text-accent"><Icon className="size-4"/></span><div><p className="text-xs font-bold">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{value}</p></div><Check className="ml-auto size-4 text-accent"/></div></article>)}</div></section><section className="border-y border-border bg-subtle px-5 py-8 sm:px-8"><p className="eyebrow">About</p><h2 className="mt-3 font-display text-xl font-bold">Designing systems people can trust.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">I am a product designer and researcher focused on making complex public services feel understandable, inclusive, and human.</p></section></div>; }