import { createFileRoute } from "@tanstack/react-router";
import { Eye, Globe2, Link2, LockKeyhole, Save, Search } from "lucide-react";
import { toast } from "sonner";
import { PageIntro } from "@/components/dashboard/ModulePage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";

export const Route = createFileRoute("/dashboard/portfolio/settings")({ head: () => ({ meta: [{ title: "Portfolio Settings — FolioX" }, { name: "description", content: "Control your FolioX public portfolio, URL, visibility, and appearance." }, { property: "og:title", content: "Portfolio Settings — FolioX" }, { property: "og:description", content: "Manage what appears on your FolioX portfolio." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: PortfolioSettings });
const controls = [[Eye,"Public profile","Allow people with your link to view your portfolio",true],[Link2,"Professional links","Show selected external professional destinations",true],[LockKeyhole,"Professional evidence","Show only evidence explicitly marked Public",true],[Search,"Search engine visibility","Allow discovery by search engines when connected",false]] as const;
function PortfolioSettings() { return <div className="space-y-8"><PageIntro eyebrow="Public presence" title="Portfolio settings" description="Control your URL, visibility, and appearance without exposing private workspace information." action={<Button onClick={()=>toast.success("Settings ready to save",{description:"This preview does not store changes yet."})} className="rounded-full"><Save/>Save changes</Button>}/><section className="grid gap-6 xl:grid-cols-[1fr_.8fr]"><div className="rounded-2xl border border-border bg-card p-6 shadow-soft"><div className="flex items-center gap-3"><Globe2 className="size-5 text-accent"/><h2 className="font-display text-lg font-bold">Public URL</h2></div><label className="mt-6 block text-xs font-bold">Username<div className="mt-2 flex h-11 overflow-hidden rounded-xl border border-input"><span className="grid place-items-center bg-subtle px-3 text-xs text-muted-foreground">foliox.me/</span><Input defaultValue="amara" maxLength={50} className="h-full rounded-none border-0 shadow-none"/></div></label><p className="mt-2 text-xs text-muted-foreground">This becomes the shareable address for your portfolio.</p></div><div className="rounded-2xl border border-border bg-card p-6 shadow-soft"><p className="eyebrow">Appearance</p><h2 className="mt-3 font-display text-lg font-bold">Focused and consistent</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">FolioX keeps your public story polished with a restrained professional presentation.</p><div className="mt-6 grid grid-cols-3 gap-2">{["Ink","Light","Warm"].map((item,index)=><button key={item} className={`h-16 rounded-xl border text-xs font-bold ${index===0?"border-accent bg-primary text-primary-foreground":"border-border bg-subtle"}`}>{item}</button>)}</div></div></section><section className="rounded-2xl border border-border bg-card p-6 shadow-soft"><h2 className="font-display text-lg font-bold">Visibility</h2><div className="mt-4 divide-y divide-border">{controls.map(([Icon,title,copy,checked])=><div key={title} className="flex items-center gap-4 py-5"><span className="grid size-10 place-items-center rounded-xl bg-accent-soft text-accent"><Icon className="size-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{copy}</p></div><Switch defaultChecked={checked}/></div>)}</div></section></div>; }